name = "hyde-hyde"
license = "MIT"
licenselink = "https://github.com/htr3n/hyde-hyde/blob/master/LICENSE.md"
description = "A simply cool Hyde inspired theme"
tags = ["blog", "theme", "hyde", "highlight.js", "font-awesome", "analytics", "comment", "personal", "syntax highlighting", "responsive", "graphcomment"]
features = ["blog", "theme", "highlight.js", "font-awesome", "responsive", "comment", "graphcomment", "portfolio"]
homepage = "https://github.com/htr3n/hyde-hyde"
min_version = "0.43"

[author]
    name = "htr3n"
    homepage = "https://htr3n.github.io"

# If Porting existing theme
[original]
    author =  "spf13"
    homepage = "http://spf13.com/"
    repo = "https://github.com/spf13/hyde"
